services: 
  go-api: 
    build: 
      context: ../..
      dockerfile: docker/dev/go.Dockerfile
    networks:
      frontend: 
        ipv4_address: 172.28.0.37
      backend:
        ipv4_address: 172.27.0.129



    # # mount the src directory to dev container to avoid copying changes all the time
    # volumes:
    #   - ../..:/go-http-devs:ro

networks:
  frontend:
    ipam:
      driver: default
      config: 
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

  backend:
    ipam:
      driver: default
      config: 
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.1
        